### ISSUE TITLE
Cant save settings on OC2

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-csp-plugin#3]
Unable to save the settings on October CMS v2.0.16

![image](https://user-images.githubusercontent.com/2263496/120154993-00eb5a00-c223-11eb-882c-9b8732425f93.png)

**Comment by tobias-kuendig** [comment]
Are you on version 1.0.6? There were some fixes regarding this issue in #2.

Also, can you share the full stack trace from your system.log?

**Comment by chrisvidal** [comment]
I did a fresh install from the composer and it served me the 1.0.5

**Comment by chrisvidal** [comment]
```
[2021-05-31 07:14:08] production.ERROR: ErrorException: Undefined property: stdClass::$font_src in /home/openhouse/public_html/plugins/offline/csp/classes/Policy.php:191
Stack trace:
#0 /home/openhouse/public_html/plugins/offline/csp/classes/Policy.php(191): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined prope...', '/home/openhouse...', 191, Array)
#1 /home/openhouse/public_html/plugins/offline/csp/classes/Policy.php(31): OFFLINE\CSP\Classes\Policy->fontSrc()
#2 /home/openhouse/public_html/plugins/offline/csp/classes/CSPMiddleware.php(79): OFFLINE\CSP\Classes\Policy->configure()
#3 /home/openhouse/public_html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(418): OFFLINE\CSP\Classes\CSPMiddleware->OFFLINE\CSP\Classes\{closure}()
#4 /home/openhouse/public_html/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(390): Illuminate\Cache\Repository->rememberForever('offline.csp.bac...', Object(Closure))
#5 /home/openhouse/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Cache\CacheManager->__call('rememberForever', Array)
#6 /home/openhouse/public_html/plugins/offline/csp/classes/CSPMiddleware.php(102): Illuminate\Support\Facades\Facade::__callStatic('rememberForever', Array)
#7 /home/openhouse/public_html/plugins/offline/csp/classes/CSPMiddleware.php(55): OFFLINE\CSP\Classes\CSPMiddleware->buildHeaders(Array)
#8 /home/openhouse/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): OFFLINE\CSP\Classes\CSPMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#9 /home/openhouse/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 /home/openhouse/public_html/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /home/openhouse/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 /home/openhouse/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/openhouse/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 /home/openhouse/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#15 /home/openhouse/public_html/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
```

**Comment by chrisvidal** [comment]
I manage to work around the issue by setting OFF the CSP, settings the value in the different tabs, then setting it back ON

**Comment by tobias-kuendig** [comment]
Thank you for this report @chrisvidal, the issue seems to be fixed in newer versions.
